feature-hw-1
kristina-salnyk/react-fundamentals-course-hw pull request #1
Opened 2023-03-20 16:48 UTC by kristina-salnyk

2023-03-21 09:28 UTC, obriukhanov requested changes

2023-03-21 09:28 UTC, obriukhanov commented on package.json
>      "@testing-library/jest-dom": "^5.16.5",
Minor:
testing-library: це є девелопмент залежністю

2023-03-21 09:28 UTC, obriukhanov commented on package.json
> +  "devDependencies": {
Minor:
Зазвичай порядок ключів в такий package.json:
- project specific (**name, version, author, private**, ... rest);
- **scripts**;
- **devDependencies**;
- **dependencies**;
- rest
Зверху до низу.

2023-03-21 09:28 UTC, obriukhanov commented on src/App.jsx
> +
Minor:
Best practice: Сlean Code
Для кращого візуального сприйняття порядок та групування імпортів важливий.
import from '[node_modules]'

import from '[own_components]'
import from '[constants]'

import from '[styles]'

(Для цього і всіх інших файлів)

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Courses/Courses.jsx
> +	);
Minor:
Для оптимізації перформанса можна використати хук useMemo.
У випадках коли массив має велику довжину або кількість рівнів вкладеності це дозволяє трохи зменшити час рендерую.

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Courses/Courses.jsx
> +						onClick={() => setCurrentView(VIEWS.CREATE_NEW_COURSE)}
Minor:
У даному випадку при кожному рендері в чайлд компонент буде прокидуватись новий інстанс функції (нове посилання об'єкта).
Можна оптимізувати хуком useCallback

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Courses/components/CourseCard/CourseCard.jsx
> +		.join(', ');
Minor:
Best practice виносити подібні речі (будь які калькуляційні/маніпуляційні дій) в хелпери.
Можна створити файл на рівні папки компонента і імпортувати.
Це дозволить покращити читаємість коду та покрити юніт тестами.

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Courses/components/CourseCard/CourseCard.jsx
> +					onClick={() => {}}
Minor:
Знову, на кожному рендері прокидується новий інстанс функції.
У даному випадку onClick треба прибрати, і хендлити відсутність опціонального пропсу на рівні **Button**

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Courses/components/SearchBar/SearchBar.jsx
> +		onSubmit(value);
Minor:
if(!value)
  onSubmit(value);

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Courses/Courses.jsx
> +	const [courses] = useState(MOCKED_COURSES_LIST);
Minor:
Не потрібно використовувати useState якщо ці данні є константою.
Тим більше не юзаючи setState.

2023-03-21 09:28 UTC, obriukhanov commented on src/components/CreateCourse/CreateCourse.jsx
> +export default CreateCourse;
Minor:
Сlean code.
Залежно від стайл гайдів узгоджених на проекті, але можна прийняти за правило не робити файл більшим за ~ 180 - 200 рядків.
Для кращої читаємості краще декомпозувати логіку (виділити ютілс/хелпери в окремі файли, додати ще 1 компонент - контейнер).

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Header/Header.jsx
> +							onClick={() => {}}
+

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Header/Header.jsx
> +	return (
Minor:
Можна скоротити

2023-03-21 09:28 UTC, obriukhanov commented on src/components/Header/components/Logo/Logo.jsx
> +export default Logo;
Minor:
Має бути new line.
Зазвичай таке правило додається до лінтер
[[padding-line-between-statements](https://eslint.org/docs/latest/rules/padding-line-between-statements)](https://eslint.org/docs/latest/rules/padding-line-between-statements)

2023-03-21 09:28 UTC, obriukhanov commented on src/constants.js
> +export const MOCKED_COURSES_LIST = [
Minor:
Не потрібно конкретизувати що це мок дані.
Коли дані будуть надходити з беку доведеться змінювати неймінг.
Тому без MOCKED_

2023-03-21 09:28 UTC, obriukhanov commented on src/helpers/dateGenerator.js
> +	return `${date.getDate()}/${date.getMonth() + 1}/${date.getFullYear()}`;
Minor:
\n

2023-03-21 10:39 UTC, kristina-salnyk commented on package.json
>      "@testing-library/jest-dom": "^5.16.5",
moved to devDependencies

2023-03-21 10:40 UTC, kristina-salnyk commented on package.json
> +  "devDependencies": {
the key order has been changed

2023-03-21 10:44 UTC, kristina-salnyk commented on src/App.jsx
> +
the import order has been fixed

2023-03-21 10:47 UTC, kristina-salnyk commented on src/components/Courses/Courses.jsx
> +	);
the rendering of the course list has been optimized using useMemo

2023-03-21 10:55 UTC, kristina-salnyk commented on src/components/Courses/Courses.jsx
> +						onClick={() => setCurrentView(VIEWS.CREATE_NEW_COURSE)}
passing the function as props has been optimized using useCallback

2023-03-21 11:29 UTC, kristina-salnyk commented on src/components/Courses/components/CourseCard/CourseCard.jsx
> +		.join(', ');
added getAuthorsListById helper function

2023-03-21 12:24 UTC, kristina-salnyk commented on src/components/Courses/components/CourseCard/CourseCard.jsx
> +					onClick={() => {}}
the callback is prepared for further implementation. Deleted at this stage. Added handling of missing optional props in the Button component

2023-03-21 12:48 UTC, kristina-salnyk commented on src/components/Courses/components/SearchBar/SearchBar.jsx
> +		onSubmit(value);
the function has been optimized

2023-03-21 13:26 UTC, kristina-salnyk commented on src/components/Courses/Courses.jsx
> +	const [courses] = useState(MOCKED_COURSES_LIST);
removed courses state

2023-03-22 09:18 UTC, obriukhanov approved these changes
LGTM
Can be merged in master

2023-03-22 10:02 UTC, kristina-salnyk commented on src/components/CreateCourse/CreateCourse.jsx
> +export default CreateCourse;
the component was optimized, added Authors, AddAuthor components, and helper functions in other files

2023-03-22 10:04 UTC, kristina-salnyk commented on src/components/Header/Header.jsx
> +							onClick={() => {}}
handler has been removed

2023-03-22 10:06 UTC, kristina-salnyk commented on src/components/Header/Header.jsx
> +	return (
the component code shortened

2023-03-22 10:19 UTC, kristina-salnyk commented on src/components/Header/components/Logo/Logo.jsx
> +export default Logo;
the padding-line-between-statements rule has been added to eslint

2023-03-22 10:22 UTC, kristina-salnyk commented on src/constants.js
> +export const MOCKED_COURSES_LIST = [
the init data has been renamed

2023-03-22 10:37 UTC, merged